# Generated by Django 5.2.12 on 2026-05-17 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaDinamica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=150)),
                ('tipus', models.CharField(max_length=50)),
                ('nivell_perill', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11)),
                ('radi_afectacio', models.IntegerField(default=5000, help_text='Metres')),
                ('data_inici', models.DateTimeField()),
                ('data_fi', models.DateTimeField()),
                ('origen_dades', models.CharField(blank=True, max_length=50, null=True)),
                ('url_font_oficial', models.URLField(blank=True, max_length=255, null=True)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('pes', models.DecimalField(blank=True, decimal_places=2, help_text='Grams', max_digits=7, null=True)),
                ('volum', models.DecimalField(blank=True, decimal_places=2, help_text='Litres', max_digits=5, null=True)),
                ('preu', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('imatge_url', models.URLField(blank=True, max_length=255, null=True)),
                ('link_compra', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menjar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('pes', models.DecimalField(blank=True, decimal_places=2, help_text='En grams per ració', max_digits=7, null=True)),
                ('volum', models.DecimalField(blank=True, decimal_places=2, help_text='Litres', max_digits=5, null=True)),
                ('preu', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('calories', models.IntegerField(blank=True, help_text='Vital per a la IA', null=True)),
                ('imatge_url', models.URLField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motxilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('pes_base', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='RiscEstatic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('tipus', models.CharField(max_length=50)),
                ('nivell_perill', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11)),
                ('radi_afectacio', models.IntegerField(default=50, help_text='Metres')),
                ('origen_dades', models.CharField(default='manual', max_length=50)),
                ('actiu', models.BooleanField(default=True)),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificultat', models.CharField(choices=[('facil', 'Fàcil - Per a tots els públics'), ('moderada', 'Moderada - Requereix certa forma física'), ('dificil', 'Difícil - Desnivell o terreny exigent'), ('molt_dificil', 'Molt difícil - Només per a experts'), ('extrema', 'Extrema - Risc elevat o equipament especial')], default='moderada', help_text='Nivell general de dificultat de la ruta', max_length=20)),
                ('nom', models.CharField(max_length=200)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('modalitat', models.CharField(choices=[('senderisme', 'Senderisme'), ('alpinisme', 'Alpinisme'), ('btt', 'Bicicleta BTT'), ('trail_running', 'Trail Running'), ('escalada', 'Escalada'), ('esqui', 'Esquí'), ('altra', 'Altra')], default='senderisme', max_length=50)),
                ('imatge_portada', models.URLField(blank=True, max_length=255, null=True)),
                ('galeria_fotos', models.JSONField(blank=True, default=list, help_text="Llista d'URLs de fotos")),
                ('es_verificada', models.BooleanField(default=False)),
                ('distancia', models.DecimalField(blank=True, decimal_places=2, help_text='En km', max_digits=8, null=True)),
                ('desnivell_positiu', models.IntegerField(default=0, help_text='En metres')),
                ('desnivell_negatiu', models.IntegerField(default=0, help_text='En metres')),
                ('temps_estimat', models.DecimalField(blank=True, decimal_places=2, help_text='En hores', max_digits=5, null=True)),
                ('track_complet', models.JSONField(blank=True, help_text='GeoJSON complet pre-unit per al mapa.', null=True)),
                ('perfil_elevacio', models.JSONField(blank=True, help_text='Array amb les dades detallades de distància i elevació', null=True)),
                ('data_creacio', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('data_naixement', models.DateField(blank=True, null=True)),
                ('biografia', models.TextField(blank=True, null=True)),
                ('url_foto_perfil', models.URLField(blank=True, null=True)),
                ('rol', models.CharField(choices=[('usuari', 'Usuari'), ('freemium', 'Freemium'), ('admin', 'Administrador')], default='usuari', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MotxillaMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.IntegerField(default=1)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.material')),
                ('motxilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.motxilla')),
            ],
        ),
        migrations.AddField(
            model_name='motxilla',
            name='materials',
            field=models.ManyToManyField(through='planner.MotxillaMaterial', to='planner.material'),
        ),
        migrations.CreateModel(
            name='MotxillaMenjar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantitat', models.IntegerField(default=1)),
                ('menjar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.menjar')),
                ('motxilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.motxilla')),
            ],
        ),
        migrations.AddField(
            model_name='motxilla',
            name='menjars',
            field=models.ManyToManyField(through='planner.MotxillaMenjar', to='planner.menjar'),
        ),
        migrations.CreateModel(
            name='Planificacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=150)),
                ('data_inici', models.DateField(blank=True, null=True)),
                ('data_fi', models.DateField(blank=True, null=True)),
                ('motxilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.motxilla')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificacions', to='planner.ruta')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planificacions', to='planner.usuari')),
            ],
        ),
        migrations.CreateModel(
            name='PressupostDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepte', models.CharField(max_length=100)),
                ('import_despesa', models.DecimalField(decimal_places=2, max_digits=7)),
                ('divisa', models.CharField(default='EUR', max_length=10)),
                ('planificacio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despeses', to='planner.planificacio')),
            ],
        ),
        migrations.CreateModel(
            name='ItinerariNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.IntegerField()),
                ('latitud', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitud', models.DecimalField(decimal_places=8, max_digits=11)),
                ('altitud', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('es_waypoint', models.BooleanField(default=True)),
                ('nom_punt', models.CharField(blank=True, max_length=150, null=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='planner.ruta')),
            ],
            options={
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Servei',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipus', models.CharField(choices=[('aigua', "Font / Punt d'aigua"), ('refugi', 'Refugi / Hostal'), ('restauracio', 'Restaurant / Bar'), ('parking', 'Aparcament'), ('salut', "Punt d'emergència / SOS"), ('electricitat', 'Càrrega elèctrica')], max_length=50)),
                ('nom', models.CharField(max_length=150)),
                ('descripcio', models.TextField(blank=True, null=True)),
                ('te_cost', models.BooleanField(default=False)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='serveis_node', to='planner.itinerarinode')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serveis', to='planner.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Tram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_geojson', models.JSONField(blank=True, help_text='Track calculat per ORS o coordenades exactes', null=True)),
                ('distancia_metres', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('desnivell_positiu', models.IntegerField(blank=True, null=True)),
                ('desnivell_negatiu', models.IntegerField(blank=True, default=0, null=True)),
                ('temps_estimat_minuts', models.IntegerField(blank=True, null=True)),
                ('node_desti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trams_arribada', to='planner.itinerarinode')),
                ('node_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trams_sortida', to='planner.itinerarinode')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trams', to='planner.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='TokenJWT2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.usuari')),
            ],
        ),
        migrations.AddField(
            model_name='ruta',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutes_creades', to='planner.usuari'),
        ),
        migrations.AddField(
            model_name='motxilla',
            name='usuari',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motxilles', to='planner.usuari'),
        ),
        migrations.CreateModel(
            name='Valoracio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacio', models.IntegerField(blank=True, null=True)),
                ('like', models.BooleanField()),
                ('data_valoracio', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valoracions', to='planner.ruta')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.usuari')),
            ],
            options={
                'unique_together': {('usuari', 'ruta')},
            },
        ),
        migrations.CreateModel(
            name='Comentari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcio', models.TextField()),
                ('data_creacio', models.DateTimeField(auto_now_add=True)),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentaris', to='planner.ruta')),
                ('usuari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.usuari')),
                ('valoracio_rel', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentari_text', to='planner.valoracio')),
            ],
        ),
    ]
