# Generated by Django 5.2.12 on 2026-05-17 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='comentari',
            unique_together={('usuari', 'ruta')},
        ),
    ]
